# markdownlint YAML configuration
---

# Default state for all rules
default: true

# ignored rules
line-length: false
no-inline-html: false
first-line-h1: false
no-emphasis-as-header: false
MD024:
  allow_different_nesting: true
  siblings_only: true